CRITICAL - 2023-09-06 12:27:01 --> syntax error, unexpected token ")"
in APPPATH\Controllers\Auth.php on line 18.
 1 SYSTEMPATH\Autoloader\Autoloader.php(291): CodeIgniter\Autoloader\Autoloader->includeFile('C:\\xampp\\htdocs\\sistem\\app\\Controllers\\Auth.php')
 2 SYSTEMPATH\Autoloader\Autoloader.php(269): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Controllers\\Auth')
 3 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Controllers\\Auth')
 4 SYSTEMPATH\CodeIgniter.php(890): class_exists('\\App\\Controllers\\Auth', true)
 5 SYSTEMPATH\CodeIgniter.php(484): CodeIgniter\CodeIgniter->startController()
 6 SYSTEMPATH\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\sistem\\public\\index.php')
CRITICAL - 2023-09-06 12:44:55 --> syntax error, unexpected single-quoted string "password", expecting "]"
in APPPATH\Controllers\Auth.php on line 31.
 1 SYSTEMPATH\Autoloader\Autoloader.php(291): CodeIgniter\Autoloader\Autoloader->includeFile('C:\\xampp\\htdocs\\sistem\\app\\Controllers\\Auth.php')
 2 SYSTEMPATH\Autoloader\Autoloader.php(269): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Controllers\\Auth')
 3 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Controllers\\Auth')
 4 SYSTEMPATH\CodeIgniter.php(890): class_exists('\\App\\Controllers\\Auth', true)
 5 SYSTEMPATH\CodeIgniter.php(484): CodeIgniter\CodeIgniter->startController()
 6 SYSTEMPATH\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\sistem\\public\\index.php')
CRITICAL - 2023-09-06 12:58:49 --> syntax error, unexpected token ";", expecting "]"
in APPPATH\Controllers\Auth.php on line 31.
 1 SYSTEMPATH\Autoloader\Autoloader.php(291): CodeIgniter\Autoloader\Autoloader->includeFile('C:\\xampp\\htdocs\\sistem\\app\\Controllers\\Auth.php')
 2 SYSTEMPATH\Autoloader\Autoloader.php(269): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Controllers\\Auth')
 3 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Controllers\\Auth')
 4 SYSTEMPATH\CodeIgniter.php(890): class_exists('\\App\\Controllers\\Auth', true)
 5 SYSTEMPATH\CodeIgniter.php(484): CodeIgniter\CodeIgniter->startController()
 6 SYSTEMPATH\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\sistem\\public\\index.php')
CRITICAL - 2023-09-06 13:01:30 --> password_hash() expects at least 2 arguments, 1 given
in APPPATH\Controllers\Auth.php on line 31.
 1 APPPATH\Controllers\Auth.php(31): password_hash('muhammad')
 2 SYSTEMPATH\CodeIgniter.php(932): App\Controllers\Auth->save()
 3 SYSTEMPATH\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
 4 SYSTEMPATH\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\sistem\\public\\index.php')
ERROR - 2023-09-06 13:02:15 --> mysqli_sql_exception: Unknown column 'created_at' in 'field list' in C:\xampp\htdocs\sistem\system\Database\MySQLi\Connection.php:295
Stack trace:
#0 C:\xampp\htdocs\sistem\system\Database\MySQLi\Connection.php(295): mysqli->query('INSERT INTO `us...', 0)
#1 C:\xampp\htdocs\sistem\system\Database\BaseConnection.php(692): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `us...')
#2 C:\xampp\htdocs\sistem\system\Database\BaseConnection.php(606): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `us...')
#3 C:\xampp\htdocs\sistem\system\Database\BaseBuilder.php(2309): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 C:\xampp\htdocs\sistem\system\Model.php(330): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\sistem\system\BaseModel.php(782): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\sistem\system\Model.php(730): CodeIgniter\BaseModel->insert(Array, false)
#7 C:\xampp\htdocs\sistem\system\BaseModel.php(692): CodeIgniter\Model->insert(Array, false)
#8 C:\xampp\htdocs\sistem\app\Controllers\Auth.php(31): CodeIgniter\BaseModel->save(Array)
#9 C:\xampp\htdocs\sistem\system\CodeIgniter.php(932): App\Controllers\Auth->save()
#10 C:\xampp\htdocs\sistem\system\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#11 C:\xampp\htdocs\sistem\system\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\sistem\public\index.php(67): CodeIgniter\CodeIgniter->run()
#13 C:\xampp\htdocs\sistem\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#14 {main}
CRITICAL - 2023-09-06 13:02:15 --> Unknown column 'created_at' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 295.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(295): mysqli->query('INSERT INTO `users` (`username`, `email`, `password`, `created_at`, `updated_at`) VALUES (\'Lutvi Wahyudi\', \'lutvi.190170110@gmail.com\', \'$2y$10$sKkr0.7XGqlAsNkaoo6Y0.sp21aKuvWU669t1YLpo5scBg1l9/UmS\', \'2023-09-06 13:02:15\', \'2023-09-06 13:02:15\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(692): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `users` (`username`, `email`, `password`, `created_at`, `updated_at`) VALUES (\'Lutvi Wahyudi\', \'lutvi.190170110@gmail.com\', \'$2y$10$sKkr0.7XGqlAsNkaoo6Y0.sp21aKuvWU669t1YLpo5scBg1l9/UmS\', \'2023-09-06 13:02:15\', \'2023-09-06 13:02:15\')')
 3 SYSTEMPATH\Database\BaseConnection.php(606): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `users` (`username`, `email`, `password`, `created_at`, `updated_at`) VALUES (\'Lutvi Wahyudi\', \'lutvi.190170110@gmail.com\', \'$2y$10$sKkr0.7XGqlAsNkaoo6Y0.sp21aKuvWU669t1YLpo5scBg1l9/UmS\', \'2023-09-06 13:02:15\', \'2023-09-06 13:02:15\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2309): CodeIgniter\Database\BaseConnection->query('INSERT INTO `users` (`username`, `email`, `password`, `created_at`, `updated_at`) VALUES (:username:, :email:, :password:, :created_at:, :updated_at:)', [...], false)
 5 SYSTEMPATH\Model.php(330): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(782): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(730): CodeIgniter\BaseModel->insert([...], false)
 8 SYSTEMPATH\BaseModel.php(692): CodeIgniter\Model->insert([...], false)
 9 APPPATH\Controllers\Auth.php(31): CodeIgniter\BaseModel->save([...])
10 SYSTEMPATH\CodeIgniter.php(932): App\Controllers\Auth->save()
11 SYSTEMPATH\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
12 SYSTEMPATH\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
13 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
14 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\sistem\\public\\index.php')
ERROR - 2023-09-06 13:09:16 --> mysqli_sql_exception: Unknown column 'created_at' in 'field list' in C:\xampp\htdocs\sistem\system\Database\MySQLi\Connection.php:295
Stack trace:
#0 C:\xampp\htdocs\sistem\system\Database\MySQLi\Connection.php(295): mysqli->query('INSERT INTO `us...', 0)
#1 C:\xampp\htdocs\sistem\system\Database\BaseConnection.php(692): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `us...')
#2 C:\xampp\htdocs\sistem\system\Database\BaseConnection.php(606): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `us...')
#3 C:\xampp\htdocs\sistem\system\Database\BaseBuilder.php(2309): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 C:\xampp\htdocs\sistem\system\Model.php(330): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\sistem\system\BaseModel.php(782): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\sistem\system\Model.php(730): CodeIgniter\BaseModel->insert(Array, false)
#7 C:\xampp\htdocs\sistem\system\BaseModel.php(692): CodeIgniter\Model->insert(Array, false)
#8 C:\xampp\htdocs\sistem\app\Controllers\Auth.php(31): CodeIgniter\BaseModel->save(Array)
#9 C:\xampp\htdocs\sistem\system\CodeIgniter.php(932): App\Controllers\Auth->save()
#10 C:\xampp\htdocs\sistem\system\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#11 C:\xampp\htdocs\sistem\system\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\sistem\public\index.php(67): CodeIgniter\CodeIgniter->run()
#13 C:\xampp\htdocs\sistem\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#14 {main}
CRITICAL - 2023-09-06 13:09:16 --> Unknown column 'created_at' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 295.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(295): mysqli->query('INSERT INTO `users` (`username`, `email`, `password`, `created_at`, `updated_at`) VALUES (\'Lutvi Wahyudi\', \'lutvi.190170110@gmail.com\', \'$2y$10$74sxqqqK6mCTW2Hh1.4wM.cyccMWz5Z60JRoOLu7i6WPJFzIEEYAm\', \'2023-09-06 13:09:16\', \'2023-09-06 13:09:16\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(692): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `users` (`username`, `email`, `password`, `created_at`, `updated_at`) VALUES (\'Lutvi Wahyudi\', \'lutvi.190170110@gmail.com\', \'$2y$10$74sxqqqK6mCTW2Hh1.4wM.cyccMWz5Z60JRoOLu7i6WPJFzIEEYAm\', \'2023-09-06 13:09:16\', \'2023-09-06 13:09:16\')')
 3 SYSTEMPATH\Database\BaseConnection.php(606): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `users` (`username`, `email`, `password`, `created_at`, `updated_at`) VALUES (\'Lutvi Wahyudi\', \'lutvi.190170110@gmail.com\', \'$2y$10$74sxqqqK6mCTW2Hh1.4wM.cyccMWz5Z60JRoOLu7i6WPJFzIEEYAm\', \'2023-09-06 13:09:16\', \'2023-09-06 13:09:16\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2309): CodeIgniter\Database\BaseConnection->query('INSERT INTO `users` (`username`, `email`, `password`, `created_at`, `updated_at`) VALUES (:username:, :email:, :password:, :created_at:, :updated_at:)', [...], false)
 5 SYSTEMPATH\Model.php(330): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(782): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(730): CodeIgniter\BaseModel->insert([...], false)
 8 SYSTEMPATH\BaseModel.php(692): CodeIgniter\Model->insert([...], false)
 9 APPPATH\Controllers\Auth.php(31): CodeIgniter\BaseModel->save([...])
10 SYSTEMPATH\CodeIgniter.php(932): App\Controllers\Auth->save()
11 SYSTEMPATH\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
12 SYSTEMPATH\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
13 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
14 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\sistem\\public\\index.php')
ERROR - 2023-09-06 13:09:58 --> mysqli_sql_exception: Unknown column 'created_at' in 'field list' in C:\xampp\htdocs\sistem\system\Database\MySQLi\Connection.php:295
Stack trace:
#0 C:\xampp\htdocs\sistem\system\Database\MySQLi\Connection.php(295): mysqli->query('INSERT INTO `us...', 0)
#1 C:\xampp\htdocs\sistem\system\Database\BaseConnection.php(692): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `us...')
#2 C:\xampp\htdocs\sistem\system\Database\BaseConnection.php(606): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `us...')
#3 C:\xampp\htdocs\sistem\system\Database\BaseBuilder.php(2309): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 C:\xampp\htdocs\sistem\system\Model.php(330): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\sistem\system\BaseModel.php(782): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\sistem\system\Model.php(730): CodeIgniter\BaseModel->insert(Array, false)
#7 C:\xampp\htdocs\sistem\system\BaseModel.php(692): CodeIgniter\Model->insert(Array, false)
#8 C:\xampp\htdocs\sistem\app\Controllers\Auth.php(31): CodeIgniter\BaseModel->save(Array)
#9 C:\xampp\htdocs\sistem\system\CodeIgniter.php(932): App\Controllers\Auth->save()
#10 C:\xampp\htdocs\sistem\system\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#11 C:\xampp\htdocs\sistem\system\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\sistem\public\index.php(67): CodeIgniter\CodeIgniter->run()
#13 C:\xampp\htdocs\sistem\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#14 {main}
CRITICAL - 2023-09-06 13:09:59 --> Unknown column 'created_at' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 295.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(295): mysqli->query('INSERT INTO `users` (`username`, `email`, `password`, `created_at`, `updated_at`) VALUES (\'Lutvi Wahyudi\', \'lutvi.190170110@gmail.com\', \'$2y$10$HafrnCG6L8QMrYNyi9wJreD74Mj.93lY2dX6GRShV1pay1t36wC0i\', \'2023-09-06 13:09:58\', \'2023-09-06 13:09:58\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(692): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `users` (`username`, `email`, `password`, `created_at`, `updated_at`) VALUES (\'Lutvi Wahyudi\', \'lutvi.190170110@gmail.com\', \'$2y$10$HafrnCG6L8QMrYNyi9wJreD74Mj.93lY2dX6GRShV1pay1t36wC0i\', \'2023-09-06 13:09:58\', \'2023-09-06 13:09:58\')')
 3 SYSTEMPATH\Database\BaseConnection.php(606): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `users` (`username`, `email`, `password`, `created_at`, `updated_at`) VALUES (\'Lutvi Wahyudi\', \'lutvi.190170110@gmail.com\', \'$2y$10$HafrnCG6L8QMrYNyi9wJreD74Mj.93lY2dX6GRShV1pay1t36wC0i\', \'2023-09-06 13:09:58\', \'2023-09-06 13:09:58\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2309): CodeIgniter\Database\BaseConnection->query('INSERT INTO `users` (`username`, `email`, `password`, `created_at`, `updated_at`) VALUES (:username:, :email:, :password:, :created_at:, :updated_at:)', [...], false)
 5 SYSTEMPATH\Model.php(330): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(782): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(730): CodeIgniter\BaseModel->insert([...], false)
 8 SYSTEMPATH\BaseModel.php(692): CodeIgniter\Model->insert([...], false)
 9 APPPATH\Controllers\Auth.php(31): CodeIgniter\BaseModel->save([...])
10 SYSTEMPATH\CodeIgniter.php(932): App\Controllers\Auth->save()
11 SYSTEMPATH\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
12 SYSTEMPATH\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
13 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
14 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\sistem\\public\\index.php')
